/*
 * This Java source file was generated by the Gradle 'init' task.
 */
public class Library {
	int a;
	String num;
	public Library(int a) {
		this.a = a;
	}
    public boolean someLibraryMethod() {
        return true;
    }
}
